### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by luisllamasbinaburo**
Added a 10ms delay by default to avoid problems with StartWith animation

Moved Animations to DefaultAnimations for easy use both in WPF and UWP
Now, you don't have to necesary create a Animations.xaml, simple references Defaults animations with
```xaml
<ResourceDictionary Source="pack://application:,,,/XamlFlair.WPF;component/DefaultAnimations.xaml"/>
```

Added BindingProperty to simultaneous set Primary and Secondary (inverted) binding to the same property without the need of converters
```xaml
<StackPanel Orientation="Horizontal" Margin="10" >
            <Border Height="100" Width="100" Margin="5" Background="Yellow"/>
            <Border Height="100" Width="100" Margin="5" Background="Pink"
                    xf:Animations.Primary="{xf:Animate BasedOn={StaticResource ScaleFromLeft}}"
                    xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource ScaleToLeft}}"
                    xf:Animations.Binding ="{Binding IsChecked, ElementName=SampleCheckBox}"
                    xf:Animations.StartWith="{xf:Animate BasedOn={StaticResource ScaleFromLeft}}"
                 >
            </Border>
            <Border Height="100" Width="100" Margin="5" Background="Yellow"/>

            <CheckBox Content="Example" x:Name="SampleCheckBox" Margin="5"/>
</StackPanel>
```

### CODE REVIEW

**Comment by XamlFlair** [comment]
I like the idea of using the "pack" statement which saves a step. do you think you can modify the Readme.md to include this as alternative way to set up the animations?

https://github.com/XamlFlair/XamlFlair/blob/master/README.md#using-a-resourcedictionary-for-base-settings

As well, can you briefly explain the 10ms delay fix?

Thank you! Greatly appreciated! 👍

**Comment by luisllamasbinaburo** [comment]
Hello @XamlFlair , thanks to you for this great library.
I have modified the readme.md to include DefaultAnimations.

Now the 10 ms delay fix. Aside from loaded animations, the most common animations that I frequenly require are simple "fadeIn fadeOut" or "slideFromX slideToX" animations, binding to a bool property.
For example:
render-slide

transform-slide

fade

In some situations, I need the element to appears "hidden". And, if I understand it correctly, that the reason why StartWith exists.
But, even using StarWith when, for example, create a new Window, I always see the initial animation For example, sliding out until it's not visible.

I was not able to (or have not found the way to) to remove this initial animation.
I believe that, although using StarWith, this method in Shared/Animations.cs
```c#
// This can be called from the three main entry-points (Primary, Secondary, and StartWith)
private static void InitializeElement(FrameworkElement element)
```
Doesn't really "priorize" StarWith animations.

Applying 10ms default delay solves my problems, but... you know... "ugly" solution

Maybe you can provide a workaround for this.

**Comment by XamlFlair** [comment]
Thanks for the readme update!  I'll include the 10ms fixand test it out, i'll merge into master as soon as I can.

**Comment by XamlFlair** [comment]
@luisllamasbinaburo I merged the changes into master. Can you give me an explanation to the new"Binding" property you added? It may need to be explained in the Readme document. Thanks.

**Comment by luisllamasbinaburo** [comment]
@XamlFlair Of course. As I said, frequently I require to make and animation that 'hides'/'shows' and element, binding to a bool property
(and I mean not really 'hide', in the meaning of really change visibility property, only to apply the animation is enough)

In this situations, I found the XamlFlair sintax to verbose. For example,
```xaml
<Border Height="100" Width="100" Margin="5" Background="Pink" ClipToBounds="True"
    xf:Animations.Primary="{xf:Animate BasedOn={StaticResource ScaleFromLeft}, Transform=Layout}"
    xf:Animations.Secondary="{xf:Animate BasedOn={StaticResource ScaleToLeft},Transform=Layout}"
    xf:Animations.PrimaryBinding ="{Binding IsChecked, ElementName=SampleCheckBox}"
    xf:Animations.SecondaryBinding ="{Binding IsChecked, ElementName=SampleCheckBox, Converter={StaticResource InverseBoolConverter}}">
```
So I make a new Binding property, that simultaneous act as a PrimaryBinding + SecondaryBinding (reversed)

Also, in my app, I create some styles, for example,
```xaml
<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
            xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
            xmlns:cor="clr-namespace:System;assembly=mscorlib"
            xmlns:xf="clr-namespace:XamlFlair;assembly=XamlFlair.WPF">

    <Style x:Key="AnimationFade">
        <Setter Property="xf:Animations.Primary" Value="{xf:Animate BasedOn={StaticResource FadeIn}}"></Setter>
        <Setter Property="xf:Animations.Secondary" Value="{xf:Animate BasedOn={StaticResource FadeOut}}"></Setter>
    </Style>

    <Style x:Key="AnimationScaleFromTop">
        <Setter Property="xf:Animations.Primary" Value="{xf:Animate BasedOn={StaticResource ScaleFromTop}}"></Setter>
        <Setter Property="xf:Animations.Secondary" Value="{xf:Animate BasedOn={StaticResource ScaleToTop}}"></Setter>
    </Style>

<!--- ..... more styles here .... --->
</ResourceDictionary>
```

That way, I can make animations in much shorter way
```xaml
    <Border Height="100" Width="100" Margin="5" Background="Pink" ClipToBounds="True"
        Style="{StaticResource AnimationScaleFromTop}"
        xf:Animations.Binding="{Binding IsChecked, ElementName=SampleCheckBox}">
```

That's the idea. The Binding property implementation can be improved, but I solved that in an "easy way". I never do big changes in project without talking with the author first.

And I also realize that, probably, we should change the Animation.Validation to contemplate the new Property

Let me know what do you think, and if I can do anything more!
Have a nice day

**Comment by XamlFlair** [comment]
@luisllamasbinaburo I haven't yet finished verifying the changes. The UWP sample crashes based on the changes regarding "pack". I believe that "pack" urls are only WPF only.

**Comment by luisllamasbinaburo** [comment]
Ups! In UWP should be something like 
```xaml
<ResourceDictionary Source="ms-appx:///##Namespace.External.Assembly##/##FOLDER##/##FILE##.xaml" />```
I'm goint to solve that and change it. Sorry!

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  Just an update for you, I will be pushing a commit that updates the Readme with the changes you made. I changed the Binding property to be called CombinedBinding and updated the validation logic. I did however revert the 10ms delay, it was too much of a global change that affects every animation. For that, you can try setting it directly on the animation that requires a flicker fix. Let me know if that works.

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  Another question, have you been able to successfully rebuild and run the XamlFlair.UWP solution and related sample ?? I ran into an issue and can't release due to the DefaultAnimations.xaml, I'm wondering if it's something on my side.

**Pull request merged**
