### PR TITLE
Added UWP DefaultAnimations

### PR DESCRIPTION
**Pull request by luisllamasbinaburo**

### CODE REVIEW

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  I updated the Header title for DefaultAnimations in the Readme.md, can you simply update the content of that section (such as sample code):

https://github.com/XamlFlair/XamlFlair/blob/master/README.md#default-animations-uwp-and-wpf-only

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  Can you see if you get errors on the UWP project? Get latest and you might get this on a rebuild of Xamlflair.UWP:

`1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(406,5): Xaml Internal Error error WMC9999: An item with the same key has already been added.`

**Comment by luisllamasbinaburo** [comment]
Sometimes. For example, if you delete the binaries, and compile again, it works.
It seems that is some kind of Visual Studio bug
https://developercommunity.visualstudio.com/content/problem/388242/often-get-task-generateappxmanifest-failed-an-item.html

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  after a git clean -fdx, everything is back to normal. Thanks 👍

**Comment by luisllamasbinaburo** [comment]
I'm really glad you are able to find a solution. I try myself with some solutions, but cannot find one that works. 
And again, thanks to you!

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  so it happened again, I can't release the UWP version, even after a git clean -fdx

image

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  I plan on making new releases by end of week. If you get a chance, let me know if you're able to build Xamlflair.UWP in release. It's stopping me from pushing a new version due to that error. It was one of the reasons I had reverted last time.

**Comment by luisllamasbinaburo** [comment]
Hi, sorry for late answer, i have been some days without access to a computer.

I still facing some ramdon error messages, but they appears and dessappears while compiling, and finally it compiles any way and app starts correctly.
I'm sure that this is a non-code related error, but the way compiler handles WPF, UWP, UNO cache. Sadly, it seems that make a little mess.

I tried everthing I can figure out to solve, but without results. If you want, we can remove UWP DefaultAnimations

**Comment by XamlFlair** [comment]
@luisllamasbinaburo  what I will do is revertbut then keep those changes in a seperate branch, and if I find a solution then I'll include it...i still think it would be a good feature to eventually include.

**Pull request merged**
